table _measures
	lineageTag: fe3edaca-7c07-4f27-99c3-2ddf28ba8f61

	measure 'Total Orders' = ```
			DISTINCTCOUNT ( f_orders[order_id] )
			
			
			```
		formatString: #,0
		displayFolder: Sales
		lineageTag: 32d97663-b238-4aee-86b3-073c0446c0fd

		changedProperty = IsHidden

	measure 'Total Revenue' = ```
			SUM ( f_order_items[price] )
			
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		displayFolder: Sales
		lineageTag: b6d994bf-34da-47b5-bf97-ad19f44edefc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Freight' = ```
			SUM ( f_order_items[freight_value] )
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: a7c151a6-4fcf-4bca-aa76-01935e2898fb

		changedProperty = IsHidden

	measure AOV = ```
			DIVIDE ( [Total Revenue], [Total Orders] )
			
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		displayFolder: Sales
		lineageTag: 4e2765a9-ce2d-427d-a955-e988b9843902

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Delivered Orders' = ```
			
			CALCULATE (
			    DISTINCTCOUNT ( f_orders[order_id] ),
			    f_orders[order_status] = "delivered"
			)
			
			```
		formatString: #,0
		displayFolder: Delivery
		lineageTag: e3aa53a8-239a-442a-975b-a70ff7c2a4af

		changedProperty = IsHidden

	measure 'Avg Delivery Days' = ```
			
			AVERAGEX (
			    FILTER (
			        f_orders,
			        f_orders[order_status] = "delivered"
			            && NOT ISBLANK ( f_orders[order_delivered_customer_date] )
			            && NOT ISBLANK ( f_orders[order_purchase_timestamp] )
			    ),
			    DATEDIFF (
			        f_orders[order_purchase_timestamp],
			        f_orders[order_delivered_customer_date],
			        DAY
			    )
			)
			
			```
		formatString: 0
		displayFolder: Delivery
		lineageTag: bda32d8b-fe7f-4ed6-a690-be7436825b4c

		changedProperty = IsHidden

	measure 'On-Time Delivery %' = ```
			
			VAR Delivered =
			    FILTER (
			        f_orders,
			        f_orders[order_status] = "delivered"
			            && NOT ISBLANK ( f_orders[order_delivered_customer_date] )
			            && NOT ISBLANK ( f_orders[order_estimated_delivery_date] )
			    )
			VAR OnTimeCount =
			    COUNTROWS (
			        FILTER (
			            Delivered,
			            f_orders[order_delivered_customer_date] <= f_orders[order_estimated_delivery_date]
			        )
			    )
			VAR DeliveredCount =
			    COUNTROWS ( Delivered )
			RETURN
			DIVIDE ( OnTimeCount, DeliveredCount )
			
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Delivery
		lineageTag: 76034799-d6cc-4bb0-aeb9-788f96879461

		changedProperty = IsHidden

	measure 'Total Reviews' = ```
			
			COUNTROWS ( f_reviews )
			
			```
		formatString: 0
		displayFolder: Reviews
		lineageTag: 7684a3aa-6990-4756-99d1-852b809d9068

		changedProperty = IsHidden

	measure 'Avg Review Score' = ```
			
			AVERAGE ( f_reviews[review_score] )
			
			```
		formatString: 0.00
		displayFolder: Reviews
		lineageTag: 38329cda-cc9a-479f-8a6e-f08d6cc0999b

		changedProperty = IsHidden

	measure 'Low Reviews %' = ```
			
			DIVIDE (
			    CALCULATE ( COUNTROWS ( f_reviews ), f_reviews[review_score] <= 2 ),
			    [Total Reviews]
			)
			
			```
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Reviews
		lineageTag: d21fc38d-f4ed-489d-9a9e-de8ca4f68767

		changedProperty = IsHidden

	partition _measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WqlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [MeasureTable = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MeasureTable", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"MeasureTable"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

